#!/bin/bash
echo "$(echo $WATER | tr -cd '[a-jA-J]' | tr '[:lower:]' '[:upper:]' | tr '[:A-J]' '[:0-9]') + $(echo $STIR | tr -cd '[k-sK-S]' | tr '[:lower:]' '[:upper:]' | tr '[:K-S]' '[:0-9]')"|bc|tr '[:digit:]' 'abcdefghij'
